# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formd',
            name='date_added',
            field=models.DateField(null=True),
        ),
    ]
